### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by jogibear9988** [PolymerLabs/uni-virtualizer#24]
How can I do Lazy Loading (DataVirtualization) ?

**Comment by straversi** [comment]
Since the recent 0.3.0 release, the API should be wide enough to implement lazy loading.

One approach would be to load a subset of your data with `scroll` or `<lit-virtualizer>`, and attach a [`rangechange`](https://github.com/PolymerLabs/uni-virtualizer/blob/master/packages/lit-virtualizer/README.md#rangechange-event) listener to the host element. When the user scrolls past some threshold index, you can load more data and update `items`.

[Example of listening for rangechange with `scroll`](https://github.com/PolymerLabs/uni-virtualizer/blob/master/packages/uni-virtualizer-examples/public/visible-indices-lit-html/index.js)
[Example of listening for rangechange with `<lit-virtualizer>`](https://github.com/PolymerLabs/uni-virtualizer/blob/master/packages/uni-virtualizer-examples/public/visible-indices-lit-element/index.js)

Let us know if you try it out! 🙂
