### ISSUE TITLE
How to not get the "[object Object]" message?

### ISSUE THREAD

**Issue by thetaPC** [PolymerLabs/uni-virtualizer#78]
I'm switching from the pre-release to the better grid branch. 

However, the custom elements in the lit-virtualizer do not render. Instead it outputs [object Object] multiple times.

Thoughts?

**Comment by kevinpschaaf** [comment]
This is likely due to multiple versions of `lit-html` being installed in `node_modules` in your project; you need to ensure that the version of lit-html that `uni-virtualizer` is using is being loaded from the same `lit-html` package as `render`/`html` that is being used.  

Please try running `npm dedupe` on your project, which should help ensure that only one version of `lit-html` exists.  Note this is good practice either way, since loading multiple compatible versions impacts your payload also.

The issue is covered in https://github.com/Polymer/lit-html/issues/1195. The upcoming 2.0 release of lit-html allow for multiple compatible versions of lit-html to be used on the same page.

**Comment by thetaPC** [comment]
I was building the branch wrong, which caused the issue. I've managed to get it built correctly. Thanks!
